# Generated by Django 4.2.4 on 2023-08-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctortb',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctortb',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
