# Generated by Django 4.2.4 on 2024-01-09 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=5000)),
                ('sports', models.ManyToManyField(to='turfapp.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opentime', models.TimeField()),
                ('closetime', models.TimeField(max_length=30)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfapp.turf')),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(max_length=30)),
                ('cost', models.CharField(max_length=30)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfapp.turf')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('players', models.CharField(max_length=30)),
                ('book_date', models.DateField()),
                ('status', models.CharField(choices=[('Approve', 'Approve'), ('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Draft', 'Draft')], default='draft', max_length=30)),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfapp.hour')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfapp.slot')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfapp.sport')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfapp.turf')),
            ],
        ),
    ]
