# Generated by Django 4.2.4 on 2023-09-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restb',
            name='non',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='restb',
            name='veg',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
