# Generated by Django 4.2.4 on 2023-08-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0002_alter_patientb_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientb',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
