# Generated by Django 4.2.4 on 2023-09-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resortb',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('rooms', models.CharField(max_length=30)),
                ('single', models.CharField(max_length=30)),
                ('double', models.CharField(max_length=30)),
                ('family', models.CharField(max_length=30)),
                ('sprice', models.CharField(max_length=30)),
                ('dprice', models.CharField(max_length=30)),
                ('fprice', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('ro_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
