# Generated by Django 4.2.4 on 2023-09-12 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resortb',
            old_name='double',
            new_name='doble',
        ),
    ]
