# Generated by Django 4.2.4 on 2023-09-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0002_rename_double_resortb_doble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resortb',
            name='doble',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='resortb',
            name='family',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='resortb',
            name='single',
            field=models.CharField(default='', max_length=30),
        ),
    ]
