# Generated by Django 4.2.4 on 2023-09-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0003_alter_resortb_doble_alter_resortb_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resortb',
            name='doble',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='resortb',
            name='family',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='resortb',
            name='single',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
